services:
    app:
        build: .
        container_name: tienda-kelly-app
        restart: unless-stopped
        working_dir: /var/www/html 
        volumes:
            - .:/var/www/html          
            - /var/www/html/node_modules 
        ports:
            - "8000:80"   
        environment:
            - APP_ENV=local 
            - APP_DEBUG=true
            - DB_HOST=db           
            - DB_DATABASE=${DB_DATABASE} 
            - DB_USERNAME=${DB_USERNAME} 
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db 
    db:
        image: mysql:8.0            
        container_name: tienda-kelly-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: MiniShopDB 
            MYSQL_ROOT_PASSWORD: secret_password
        volumes:
            - dbdata:/var/lib/mysql
        
volumes:
    dbdata: